---
output: github_document
always_allow_html: yes
---

```{r setup, include=FALSE}

library(htmltools) 
library(knitr)
library(tidyverse)

options(knitr.kable.NA = '')
```


```{r, echo = FALSE}
csv_url <- "https://raw.githubusercontent.com/tiernanmartin/datasets/master/wa-state-agencies/data/wa-state-agencies.csv"

link <- tags$a("here") %>% tagAppendAttributes(href = csv_url, download = NA, target = "_blank")
```

## Washington State Agencies

A list of the agencies in Washington State and their respective acronyms.

Download the data `r link`.

<a href="https://raw.githubusercontent.com/tiernanmartin/datasets/master/wa-state-agencies/data/wa-state-agencies.csv" download target="_blank">here</a>


```{r, results='asis', echo=FALSE,message=FALSE}
here::here("wa-state-agencies/data/wa-state-agencies-data-dictionary.csv") %>% 
  read_csv(na = "NA") %>% 
  kable()
```

## License

Data license: [CC Attribution 4.0 License](http://creativecommons.org/licenses/by/4.0/) · Data source: [Access Washington](https://access.wa.gov/agency.html) 